schema_version = "1.0.0"
id = "luna_engine_io"
version = "2.0.0"
name = "Luna Engine IO Tools"
tagline = "Import/export Luna Engine model files and import/export AnimClip animation data"
maintainer = "Pcniado"
type = "add-on"
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-only"]
tags = ["Import-Export", "Animation"]
